### PR TITLE
WIP: add auth template

### PR DESCRIPTION
**Pull request by wwall3r**
Adds a simple auth template which supports Svelte Kit's SSR and client-side loading along with proper session hooks.

Test locally (after cloning this branch):
```
# make a new sveltekit project
$ npm init svelte@next blank
# Choose "skeleton"
# Should work with either TypeScript or JS
$ cd blank
$ npx apply --auth true ../path/to/svelte-supabase
# edit .env file to point at a running supabase project (local or app.supabase.io is fine)
# edit src/routes/auth/example.js to point a table in your supabase project which only authenticated users can read
$ npm install
$ npm run dev
```
Then load http://localhost:3000/auth/example

## How it works
This largely follows the guide and outline at https://nikolas.ws/supabase-auth-with-sveltekit and https://github.com/ashleyconnor/sveltekit-supabase-demo. In order to use plain forms with progressive enhancement, we add endpoints at `/api/auth/login`, `/api/auth/signup`, and `/api/auth/logout` to which the form can post. These endpoints log in via the `supabase` api and then set the appropriate cookies from the session. ~For client side use of the `supabase` api, it adds the ability to listen to updates to `document.cookie` via `lib/auth/cookie-change.js` (since `window.cookieStore` is still baking) and parses the token from those cookies and calls `supabase.auth.setAuth()` with it.~ Client-side use of `supabase` calls are avoided in favor of SvelteKit's preferred method of using "page endpoints" to load data.

The endpoints have some basic redirect support so that the user is returned to the page from which they came. They also have some naive error handling (there is probably a better way to do that).

The `hooks.js` file adds hooks for ensuring that the user object and token exists in the session, which is mapped by the `getSession` hook.

## Questions

I'm fairly new to Supabase, so I am not entirely sure what the best-practice workflow is for the `access_token`, `refresh_token`, and `expires_at` portions of the session. Please feel free to give feedback. I am fairly sure a robust implementation would also need to go through OWASP's checklist for CSRF and other vulnerabilities.

## Still TODO
- [ ] Figure out why first `Preset.instructs` aren't showing
- [x] Progressive enhancement example (see the [form action from Svelte Kit](https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/src/lib/form.ts))
- [ ] Forgot password example
- [ ] Password change example
- [ ] Magic Link example
- [ ] Provider example
- [x] ~Go look for a cookieStore polyfill lib instead of rolling our own~ cookie listener hack was removed in favor of page endpoints
- [x] Support `refresh_token`
- [ ] Helper for checking JWT expiration before client-side requests

### CODE REVIEW

**Comment by ANorseDude** [comment]
Oh man, if you could finish this up I would be incredibly impressed, but also so happy. 

Any ETA on it?

**Comment by ANorseDude** [comment]
I read a discussion about this here, regarding tokens becoming invalid and such, 

https://github.com/supabase/supabase/discussions/5218#discussioncomment-2100170

Might give some inspiration of how to set overcome some of the problems. 

(Sorry that I cannot be more of help)

**Comment by wwall3r** [comment]
There's not really an ETA because this is coming out of a side project being worked by a friend and myself.

However, I do have some updates which I will bring over to this PR shortly:
- I got rid of the "express-ification" (which I thought was a little hacktastic and appeared to blow up in a recent Svelte Kit upgrade)
- I had a look at a `cookieStore` polyfill. That API is entirely async and as such was not a good drop-in replacement for what I already have in the PR
- Some handling of the refresh token in `src/hooks.js`. Whether or not you choose to provide it should probably be up to the application (i.e. commented-out by default). I will have a look at that comment and dig into that a little further.
- A wrapper for calls to the supabase API from the client: If the user's JWT access token expires while looking at the page, the next call to the supabase API will result in a 500. Therefore, I have a wrapper function which looks something like this: 
```typescript
import supabase from '$lib/db';

export default async <T>(cmd: () => Promise<T>): Promise<T> => {
	// check for JWT expiration
	const session = supabase.auth.session();
	if (session && session.expires_at * 1000 <= Date.now()) {
		console.log('session expired at ' + new Date(session.expires_at * 1000));
		// TODO: handle expired session
		// if session expired
		// hit auth/refresh endpoint (since refresh cookie is hidden to JS currently)
		// success -> continue
		// error -> redirect to login?
	}

	const { data, error } = await cmd();

	if (error) {
		throw new Error(error.message);
	}

	return data;
};
// called like: wrap(() => supabase.from('table')...)
```
Edit: and I suppose I'll go figure out why I didn't see an email when you commented. Apologies for the delay.

**Comment by weepy** [comment]
looks fab - look forward to the new changes ^_^

**Comment by weepy** [comment]
Hiya - I was just trying this out and I was getting the following error when I sign up : 
```
> svelte-kit dev "-p" "3020"


  SvelteKit v1.0.0-next.286

  local:   http://localhost:3020
  network: not exposed
  network: not exposed

  Use --host to expose server to other devices on this network


/Users/jonahfox/dev/blank/node_modules/.pnpm/@supabase+gotrue-js@1.22.2/node_modules/@supabase/gotrue-js/dist/main/GoTrueApi.js:342
                throw new Error('Auth session missing!');
                      ^

Error: Auth session missing!
    at GoTrueApi.setAuthCookie (/Users/jonahfox/dev/blank/node_modules/.pnpm/@supabase+gotrue-js@1.22.2/node_modules/@supabase/gotrue-js/dist/main/GoTrueApi.js:342:23)
    at updateAuthCookie (/src/lib/auth/helper.js:60:41)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Do you know what it means ?

**Comment by wwall3r** [comment]
@weepy there are definitely some updates for the newest version of Svelte Kit, so lemme get those in and you can try it again. I think the commit here is working against `v1.0.0-next-260`.

**Comment by wwall3r** [comment]
See today's updates, and then ensure you followed the instructions exactly. If you continue to get errors, please check your `.env` file.

Edit: I tested the last commit against `v1.0.0-next-286`

**Comment by wwall3r** [comment]
For progressive enhancement, you probably should just use the [form action from Svelte Kit](https://github.com/sveltejs/kit/blob/master/packages/create-svelte/templates/default/src/lib/form.ts) as a part of the sveltekit demo app (which I did not use in the tests since I opted for the skeleton project). That thing seems useful enough that it should be in its own package or in a utility package as opposed to just in the default demo app template.

**Comment by weepy** [comment]
Hey thanks - sorry for the delay - I'm going to check this today.

**Comment by weepy** [comment]
Hey thanks for this - so it worked ! Well mostly .. 

Couple of points

* After validating the email - it redirects to the route /?auth_token=xxxxxx 
* I'm thinking this should be handled in some way? Or is it entirely up to the user?
* Also after this redirect you are actually logged out (even though I was logged in before)

and
* I set up a todos table that can only be seen by authenticated users.
* I can see that the query that happens in the <script context="module"> returns an empty list 
* The client side query on the client side works correctly.
* So in this case I get a flash in the browser after the client side pull. 

Happy to help if I can.

**Comment by wwall3r** [comment]
@weepy the email workflows are still on my list to handle. Please feel free to take a crack at them if you like.

It sounds like you might be using a project on supabase.io rather than the local `supabase start`. I will have to go back and double-check any differences with that.

**Comment by weepy** [comment]
I can certainly have a look at flows when I get to it. I was more concerned
about the db lookups not working. You are right - the db is remote on super
base.

**Comment by robots4life** [comment]
Boom. So happy I just discovered this. After a solid workflow for SvelteKit auth with SSR. :rocket:

**Comment by wwall3r** [comment]
I'm back to working on this regularly. I think the size here warrants moving most of it off to its own package, which the template here can add to `package.json` and then apply. Then the "demo app" can be internal to that package, since I think a real application would currently be either heavily modifying or removing that altogether after applying the template.

That would also prevent duplication and rot across everyone's applications in addition to making it easier to add to an existing project.

**Comment by wwall3r** [comment]
In the event anyone finds this, you're probably looking for [Supabase's Svelte Kit Auth Docs](https://supabase.com/docs/guides/auth/auth-helpers/sveltekit) instead.

**Pull request closed without merging**
